export enum ESTADO_SOLICITUD_MULTIMEDIA_ENUM {
  PENDIENTE = 'PENDIENTE',
  DENEGADA = 'DENEGADA',
  APROBADA = 'APROBADA',
  CADUCADA = 'CADUCADA',
  ELIMINADA = 'ELIMINADA',
  EMAIL_NO_VERIFICADO = 'EMAIL_NO_VERIFICADO',
}
